package realizations;

/**
 * Created by chris on 18.01.2018.
 */
public enum  RealizationError {
    ERROR_PARTITION,
    ERROR_4_COLORING,
    ERROR_CATERPILLAR,
    ERROR_SIZE,
    ERROR_NOT_CIRCULAR,
    ERROR_NOT_2TREE,
    ERROR_SUBGRAPH_SHORT_EDGES_ROOTED,
    ERROR_SUBGRAPH_NOT_SPANNING,
    ERROR_SUBGRAPH_INDUCED_SHORT_EDGES_IS_NOT_A_TREE,
    ERROR_HEIGHT_LONG_EDGES,
    ERROR_HAMILTONIAN,
    ERROR_NOT_WHEEL
}
