package model;

/**
 * Created by chris on 05.12.2017.
 */
public enum State {
    NOTHING,
    ADD_VERTEX,
    ADD_VERTEX_WITH_DISTANCE,
    ADD_VERTEX_WITH_DISTANCE_2_VERTICES,
    ADD_EDGE,
    SELECT_FIRST_VERTEX,
    SELECT_SECOND_VERTEX,
    SELECT_THIRD_VERTEX,
    DELETE_VERTEX,
    DELETE_EDGE,
    MOVE_VERTEX,
    MOVE_VERTEX_DESTINATION,
    CLICK_STATE,
    SELECT_PARTITION_EDGE
}
